### ISSUE TITLE
feature request: set window urgent on notification when unfocused (Linux, X11)

### ISSUE THREAD

**Issue by 4nd3r** [yafp/ttth#100]
should be possible with electron.

see how mattermost did it: https://github.com/mattermost/desktop/issues/122, https://github.com/mattermost/desktop/pull/221, https://github.com/mattermost/desktop/pull/200

**Comment by yafp** [comment]
Hi again,

this sounds interesting. Gonna check what i can fetch from your sources.

**Comment by 4nd3r** [comment]
also, there should be somekind of hint on service tab too - if you focus ttth and service with notification is unfocused, you should be able to figure out which service made ttth urgent.

**Comment by yafp** [comment]
You mean like some kind of unread message counter displayed for each service on the service UI?

**Comment by 4nd3r** [comment]
unread message counter sounds like too much hassle. rather just change font style/color depending if service has "unread notifications".

**Comment by yafp** [comment]
therefor i need a method to realize if a user has then read the previously unread message. otherwise i am unable to reset the UI hint.

Do you see the problem?

**Comment by yafp** [comment]
Note to myself:
electrons browserwindow has support for flashing to look urgent - see https://electronjs.org/docs/api/browser-window#winflashframeflag

**Comment by 4nd3r** [comment]
there is some information in the internet, that flashFrame is windows only.

for linux, you could use `shell.Beep()`, which in turn makes audible bell and that can be configured also as visual bell. and bell makes window urgent. but that might annoy some people, so it should be configurable maybe?

**Comment by yafp** [comment]
according to the electron docs it is NOT windows only.

**Comment by yafp** [comment]
in 1.5.0 it is implemented as follows:
* if the timed routine finds any unread message, the window gets flagged as urgent
* if the timed routine finds no unread messages, the flag is unset.

**Comment by yafp** [comment]
regarding peep:

https://electronjs.org/docs/api/shell#shellbeep
