### ISSUE TITLE
Mac shortcuts

### ISSUE THREAD

**Issue by sceptiq** [yafp/ttth#11]
## Expected Behavior
cmd+, => preferences
cmd+h => hide window
... 

## Actual Behavior
nothing happens :)

**Comment by sceptiq** [comment]
yep, 

hide is NOT minimise  :)

**Comment by sceptiq** [comment]
cmd+h minimises the window but won't hide it

**Comment by yafp** [comment]
in 1.3.0 it should be as follows:
- cmd +h = hide (resume via tray)
- cmd + m = minimize
- cmd + k = maximize
