### ISSUE TITLE
Add Proxy settings section

### ISSUE THREAD

**Issue by ashed** [yafp/ttth#177]
Telegram service cannot connect without MTProxy

**Describe the solution you'd like**
Add Proxy settings section

**Describe alternatives you've considered**
Official and unofficial Telegram desktop clients have option to connect via proxy

**Comment by yafp** [comment]
@ashed 
Hi ... and thanks for the idea. I'll see what i can do and report back

**Comment by yafp** [comment]
Am i right that MtProxy is an open source Telegram proxy server?

I found this: 
* https://github.com/TelegramMessenger/MTProxy
* https://www.npmjs.com/package/@mtproto-org/mtproxy

but i am unsure so far how to include this into ttth.
I have to understand the use-case and workflow first i guess.

Right now ttth is just accessing https://web.telegram.org/
I guess using that proxy i would need to include the proxy code into ttth and then access the telegram web url using the proxy. Is that correct so far?

**Comment by ashed** [comment]
>>>I guess using that proxy i would need to include the proxy code into ttth and then access the telegram web url using the proxy. Is that correct so far?
Yes, that's right.
On some countries access to Telegram-related resources (e.x. web.telegram.org, telegra.ph etc) are blocked.
And it is impossible to get access to this resources with **ttth** without proxy (prefferable MTProxy) or TOR.

**Comment by ashed** [comment]
ttth-1.8.20200228-linux-x86_64

Ooops, the service telegram_SKBgItjr30I7BgVtIXJKt7Qu crashed.

**Comment by ashed** [comment]
Ooops, the service telegram_wTA9siNh5bKZWOdbmtvZtT28 crashed.
It is an error on main auth form of telegram.
Would you fix it?

**Comment by ashed** [comment]
Screenshot from devtools, connected to telegram service in ttth

[ttth-telegram-dev-tools-2020-08-09--17-48-51.png](https://imgur.com/0hufp5T)

**Comment by yafp** [comment]
Hi @ashed 

please correct me if i am wrong - but your last 3 comments have nothing to do with this issue (Add proxy..) - or am i wrong?
Mixing topics in a single issue is far away from perfect ;)

I guess your issue is related with #184

**Comment by yafp** [comment]
@ashed
i wasn't working on this project for quite a long time.
I am no longer using telegram and am therefor not considering working on this particular issue.
sorry for the long wait without outcome.
