### ISSUE TITLE
[Feature Request] Support Spotify WebPlayer

### ISSUE THREAD

**Issue by philipphutterer** [yafp/ttth#192]
Unfortunately, using the Custom URL option did not work. Also changing the user-agent did not result in the desired behavior, although this user-agent is used by my browser where [the web player](https://open.spotify.com) works.

**Comment by yafp** [comment]
Hi @philipphutterer 

first of all - thanks for the issue ;)

i'll take a look on that later. I don't have a spotify account myself - so testing might be a problem for me. i'll update this post in the next days to let you know if i think i can add support for it or not.


Greetings

**Comment by yafp** [comment]
@philipphutterer 

> Unfortunately, using the Custom URL option did not work. 

could you tell me what does not work?

![ttth_spotify](https://user-images.githubusercontent.com/67605/82841464-79179500-9ed6-11ea-997a-dad4bbf8a2c6.png)

**Comment by philipphutterer** [comment]
In the normal browser version you are able to log in to listen to music. In ttth you are only redirected to download the app or sth like that.

**Comment by yafp** [comment]
Hi,

i can listen to some promoted things there ... but i really don't know what spotify is supposed to be like and what magic spotify is doing in the background.

ttth is more or less a browser - opening url's in tabs - with some service specific inject code to provide goodies.

If opening the spotify url in ttth results in another content then opening it in your default browser - using the same browser-agent ...then it feels like some strange voodoo on the spotify side.

*wondering*

**Comment by philipphutterer** [comment]
Okay after searching around some more i think i got it. Spotify uses DRM to play their contents and the browser therefore must have a plugin what Firefox, Chrome and Safari all have. Because Chromium isnt Chrome it does not have this plugin (called Widevine). And since Electron is based on Chromium its missing this plugin s.t. the starting page might that in order to serve the correct content.

[This brave issue thread](https://community.brave.com/t/spotify-web-player-doesnt-work/34180) was quite helpful.

**Comment by philipphutterer** [comment]
I also tried to navigate directly to the spotify web player within an electron instance and it did not work either. Then i changed the user-agent properly s.t. "electron" was no longer in there and it worked properly. Another thing i recognized is, that you use electrons ```<webview>``` tag that implicitly uses an iframe. i am not sure but maybe this could also be a problem somehow?

**Comment by yafp** [comment]
> Okay after searching around some more i think i figured it out. Spotify uses DRM to play their contents and the browser therefore must have a plugin what Firefox, Chrome and Safari all have. Because Chromium isnt Chrome it does not have this plugin (called Widevine). And since Electron is based on Chromium its missing this plugin s.t. the starting page might that in order to serve the correct content.
> 
> Edit: Actually i tried it and it works on Chromium. Sorry for the incorrect statement above.
> 
> [This Brave issue thread](https://community.brave.com/t/spotify-web-player-doesnt-work/34180) was quite helpful.

thanks that info is valuable.

**Comment by yafp** [comment]
> I also tried to navigate directly to the spotify web player within an electron instance and it did not work either. Then i changed the user-agent properly s.t. "electron" was no longer in there and it worked properly. Another thing i recognized is, that you use electrons `<webview>` tag that implicitly uses an iframe. i am not sure but maybe this could also be a problem somehow?

i'll play around with it if i can find some time

**Comment by yafp** [comment]
@philipphutterer 
sorry for the long break - i was not able to work on this project now for several weeks.
I will try to start working on it, but to be honest i don't see a chance to work on this particular issue.

Will most likely focus on updating the inner core with the next versions and not by adding more services in the near future.

Therefor i am closing this for now - sorry again for the long wait without outcome.
