### ISSUE TITLE
F3 does not work on MAC

### ISSUE THREAD

**Issue by sceptiq** [yafp/ttth#21]
hiding the menu with ```f3``` doesn't work, nothing happens pressing ```f3```

**Comment by yafp** [comment]
The command 

> win.setMenuBarVisibility(visible)

is only available for Windows and Linux. See: https://electronjs.org/docs/api/browser-window#winsetmenubarvisibilityvisible-windows-linux

I guess its related with the mac-specific menu-handling.

Gonna add a note to the readme

**Comment by yafp** [comment]
Starting with the upücoming 1.2.0: 

The menu-entry will be disabled on macOS
