### ISSUE TITLE
slack session doesn't survive application reload

### ISSUE THREAD

**Issue by sceptiq** [yafp/ttth#22]
restarting or reloading the app drops me out of my slack "workplace" and brings me back to the Wellcome to slack stuff

but it does NOT forget who am I just need to reenter my "workspace"

**Comment by yafp** [comment]
Slack is currently using the url: https://slack.com for rthe webview.
As i don't use Slack myself i am unable to test at all for this service.

I assume the problem exists because the service is using the wrong url as startpoint.
Could you tell me your url after login to slack in a classic browser?

**Comment by yafp** [comment]
https://$WORKSPACENAME.slack.com

So - to know the workspace name of a user we would need to ask while enabling the service itself. Similar to mattermost.

**Comment by yafp** [comment]
Version 1.2.0 might fix this - lets hope my change works ;)
