### ISSUE TITLE
Creating a website for ttth (github-pages)

### ISSUE THREAD

**Issue by SuhailSumra** [yafp/ttth#97]
Hi this is just to write to you that i am a 17 year old website developer and i would like to contribute to the project by creating a website for ttth if you dont mind.
i look forward to your answer.

regards,
suhail

**Comment by yafp** [comment]
Hi SuhailSumra,

first of all thanks for the offer.

So far i was focused on the code of ttth and was not evben thining about a website for it. If you are willing to contribute that's fine - i could easily host it via github pages.

Keep in mind that this is an open source project and that i can't offer any money for your work.
The only reward i can offer is to add you to the contributor list of this project.

If that's fine for you - feel free to create a website and show me a preview. I would be happy to publish it then.

Looking forward to hear from you

Best regards

**Comment by SuhailSumra** [comment]
Hey Fidel,
Thank You So Much I am just doing for the sake of open-source I want to be a part of it and just be a part of it always 😊 I promise to start on the website as soon as possible and give you a demo of it have a great day ahead!

Sent from Windows Mail

**Comment by yafp** [comment]
Just a short & incomplete list of items i would like to be included on a website:

* License informations or link
** https://github.com/yafp/ttth/blob/master/LICENSE

* Some kind of UI screenshot
** might be easiest to use https://raw.githubusercontent.com/yafp/ttth/master/.github/screenshots/ui_latest.png as it should always gibe the latest stable UI

* Link to issues:
** https://github.com/yafp/ttth/issues

* Some kind of download link
** https://github.com/yafp/ttth/releases (shows all releases)
or
** https://github.com/yafp/ttth/releases/latest (shows only the latest release)

**Comment by SuhailSumra** [comment]
Sure Fidel I will include all these things and if u don't mind can I just be the co-founder of the ttth? I mean if you don't mind I will work for free and provide all the support towards the website. I can develop websites and will provide LTS towards the project I am just 17 years old and I think it will make an impact on my CV as a co-founder or even as the Lead Front-End Engineer.
Thank You


Sent from Windows Mail

**Comment by yafp** [comment]
@SuhailSumra 
sorry but i am smelling questionable motivation here.

A co-founder should co-found something, a lead front-end engineer should design something ... not just building some html/js/css code which i can more or less generate as well via the github-pages generator.

I wish you all the best .... with another project.

Bye

**Comment by SuhailSumra** [comment]
ah well I am sorry then…I am almost done working on the project just some few more elements to go and done! okay I am sorry and just adding me to the contributors is enough!

Sent from Windows Mail
