### ISSUE TITLE
feature request: hide tray icon

### ISSUE THREAD

**Issue by 4nd3r** [yafp/ttth#98]

**Comment by yafp** [comment]
Hi,

again thanks for the issue ;)

As i am curious: why would you hide the tray icon? It offers some functions (show window) which are only accessible via the tray (at least on some os'es)

**Comment by 4nd3r** [comment]
tray concept is unneccesary with tiling window manager. but i want to have systray just in case some weird app decides to hide there instead of closing. for apps, i use daily, i don't want them in my tray.

**Comment by yafp** [comment]
alright i guess this would need a new checkbox on the setting UI for disabling the tray

I'll see if i can implement it

**Comment by yafp** [comment]
Should be implemented in the upcoming version 1.5.0.

The setting can be set, but needs an app re-launch to be active in the current version. If that works for you in 1.5.0 i'll try to fine tune it later on.
