### ISSUE TITLE
can't see notifications?

### ISSUE THREAD

**Issue by 4nd3r** [yafp/ttth#99]

**Comment by yafp** [comment]
Hi,

thx for the issue.

Just to clarify: what kind of notifications are we talking about?
If ttth is not in focus on my linux boxes i do get notifications on linux (arch/ubuntu)

What os are you using, which ttth version?

**Comment by 4nd3r** [comment]
i'm using debian, i3 and riot.im - tho, there shouldn't be anything specific really, because i can see notifications fine with firefox and chromium.

notifications are enabled in riot, but i don't see them when ttth is unfocused or hidden to tray.

**Comment by 4nd3r** [comment]
did some testing with https://www.bennish.net/web-notifications.html

nothing.

![image](https://user-images.githubusercontent.com/7166727/63759379-11400980-c8c6-11e9-990a-0f055c845f2d.png)

i added this url to ttth using nextcloud service.

it shouldn't matter what kind of service i use for custom url?

**Comment by yafp** [comment]
If i 

* add your url as custom service in ttth 1.4.0, 
* press "authorize" and then 
* the "show" button 

i do get a notification on Arch Linux.

**Comment by 4nd3r** [comment]
hmm, looks like i'm missing somekind of dependency, because in terminal i see:

`libnotify-WARNING **: 12:36:13.263: Failed to connect to proxy`

> For custom urls i would always use the service type "Custom URL" - at the bottom of the service type dropdown.

ahaa, there really is, but hidden because i didn't notice scrollbar. haha.

**Comment by yafp** [comment]
> > For custom urls i would always use the service type "Custom URL" - at the bottom of the service type dropdown.
> 
> ahaa, there really is, but hidden because i didn't notice scrollbar. haha.

yeha ;)

**Comment by yafp** [comment]
> hmm, looks like i'm missing somekind of dependency, because in terminal i see:
> 
> `libnotify-WARNING **: 12:36:13.263: Failed to connect to proxy`

Please check if installing libnotify solves the issue and report back. Thanks

**Comment by 4nd3r** [comment]
libnotify is installed, but i don't have notification daemon, because firefox/chromium can display notifications without that. if i install notification daemon, for example `dunst`, then i can see notifications.

now, i'm not sure if this is a bug, but rather annoyance. maybe add some lines about that to README?

**Comment by yafp** [comment]
> now, i'm not sure if this is a bug, but rather annoyance. maybe add some lines about that to README?

Good question.
I guess i add it to the FAQ or 'Known issues' section of the documentation.

**Comment by yafp** [comment]
Added it to docs/KNOWN_ISSUES.md in my dev environment. should be commited to github in the next days.
